from datetime import datetime, timezone
from typing import Any, Protocol


def utcnow() -> str:
    return datetime.now(timezone.utc).isoformat()


class Database(Protocol):
    def get_setting(self, key: str, default: str = "") -> str: ...
    def set_setting(self, key: str, value: str) -> None: ...
    def is_maintenance(self) -> bool: ...
    def set_maintenance(self, enabled: bool) -> None: ...
    def upsert_user(self, user_id: int, username: str | None, first_name: str | None) -> None: ...
    def set_user_verified(self, user_id: int, verified: bool = True) -> None: ...
    def is_user_verified(self, user_id: int) -> bool: ...
    def get_user(self, user_id: int) -> dict[str, Any] | None: ...
    def create_order(
        self, user_id: int, pack_id: str, pack_name: str, proxy_count: int, amount: float
    ) -> int: ...
    def set_order_trx(self, order_id: int, trx_id: str) -> None: ...
    def get_order(self, order_id: int) -> dict[str, Any] | None: ...
    def get_user_orders(self, user_id: int, limit: int = 10) -> list[dict[str, Any]]: ...
    def get_pending_orders(self) -> list[dict[str, Any]]: ...
    def approve_order(self, order_id: int, proxies: list[str]) -> bool: ...
    def reject_order(self, order_id: int) -> bool: ...
    def cancel_order(self, order_id: int, user_id: int) -> bool: ...
    def get_available_proxies(self, count: int) -> list[str]: ...
    def add_proxies(self, proxies: list[str]) -> int: ...
    def count_available_proxies(self) -> int: ...
    def trx_exists(self, trx_id: str) -> bool: ...
    def get_user_stats(self, user_id: int) -> dict[str, int]: ...
